"""
https://projecteuler.net/problem=1


Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms

@author: https://github.com/aitorp6
"""

prev,curr = 0 , 1
result = 0

while prev + curr  <= 4e6:
    prev, curr = curr, prev + curr
    result += curr if curr % 2 == 0 else 0  

print("The sum of the even-valued terms is {}.".format(result))